# Generated by Django 2.2.6 on 2021-05-21 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст вашего комментария', verbose_name='Текст записи')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Дата, устанавливается автоматически', verbose_name='Дата комментария')),
                ('author', models.ForeignKey(help_text='Укажите автора комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('post', models.ForeignKey(help_text='Прокомментируйте запись', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='Комментарий к записи')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
