# Generated by Django 2.2.6 on 2021-10-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211006_2016'),
        ('posts', '0011_auto_20211006_2107'),
    ]

    operations = [
    ]
